### ISSUE TITLE
Is it possible to turn off the Snow in some bioms?

### ISSUE THREAD

**Issue by Axelthetwo** [OhRetro/forever-winter-datapack#1]
Hi, I have a simple question because I do not know nothing about coding. Is it possible to turn off snow and snow particles in hot biomes? And if so, how can I do that?

**Comment by OhRetro** [comment]
Well, if you go to "data/minecraft/worldgen/biome" and delete for example "desert.json", the settings would go back to minecraft's default desert.json settings, meaning that the desert biome won't be snowing anymore, but you'll need to do this for other subdirectories like "fw1_20/data/minecraft/worldgen/biome" for example, otherwise minecraft will complain about validation error

**Comment by Axelthetwo** [comment]
It works, thank you. I should have thought of this earlier, just to delete the files.
